### ISSUE TITLE
AttributeError: module 'icecube.phys_services' has no attribute 'I3SPRNGRandomService'

### ISSUE THREAD

**Issue by fiedl** [fschmuckermaier/POCAM_scripts#2]
I've encountered the issue

> AttributeError: module 'icecube.phys_services' has no attribute 'I3SPRNGRandomService'

when running the [`all_in_one_POCAM.py`](https://github.com/fschmuckermaier/POCAM_scripts/blob/master/scripts/all_in_one_POCAM.py) locally on macOS.

I've found this issue on slack:
https://icecube-spno.slack.com/archives/C02KQL9KN/p1576662686094900

> It is not built, however, because SPRNG is not in the py3-series toolsets. You need to set --use-gslrng

Locally, I was able to fix it by installing the missing library:

```
[2020-04-15 18:55:27] fiedl@fiedl-mbp ~/icecube/builds/2020-04-15_combo_merge-clsim-hole-ice
▶ brew tap IceCube-SPNO/homebrew-icecube
▶ brew install icecube-spno/icecube/sprng2

[2020-04-15 20:03:53] fiedl@fiedl-mbp ~/icecube/builds/2020-04-15_combo_merge-clsim-hole-ice
▶ cmake -D CMAKE_BUILD_TYPE=Debug -D SYSTEM_PACKAGES=true -D Python_ROOT=/usr/local/opt/python/ ~/icecube/combo

-- gsl
-- + gsl/gsl_rng.h found at /usr/local/include
-- + /usr/local/lib/libgsl.dylib
--
-- sprng
-- + sprng/sprng.h found at /usr/local/include
-- + /usr/local/lib/libsprng.a

[2020-04-15 20:04:35] fiedl@fiedl-mbp ~/icecube/builds/2020-04-15_combo_merge-clsim-hole-ice
▶ ./env-shell.sh make -j 4
```

Now, the missing service is there:

```
[2020-04-15 20:06:51] fiedl@fiedl-mbp ~/icecube/POCAM_scripts master ⚡
▶ icetray-inspect phys-services |grep SPRNG
  I3SPRNGRandomServiceFactory (C++ ServiceFactory)
```

**Comment by fschmuckermaier** [comment]
Replaced I3SPRNGRandomService with I3GSLRandomService.
See also:
https://icecube-spno.slack.com/archives/C02KQL9KN/p1576662686094900
