### ISSUE TITLE
TypeError: I3CLSimMakePhotons() got an unexpected keyword argument 'ParallelEvents'

### ISSUE THREAD

**Issue by fiedl** [fschmuckermaier/POCAM_scripts#4]
```
[2020-04-15 20:10:19] fiedl@fiedl-mbp ~/icecube/POCAM_scripts master ⚡
▶ python scripts/all_in_one_POCAM.py --gcd-file=~/icecube/gcd/GeoCalibDetectorStatus_IC86.55697_corrected_V2.i3.gz
INFO (I3Tray): Adding Anonymous Module of type 'I3InfiniteSource' with name 'I3InfiniteSource_0000' (I3Tray.py:76 in _create_name)
INFO (I3Tray): Adding Anonymous Module of type '<class 'generatePOCAM_Module.GeneratePOCAM_Module'>' with name 'GeneratePOCAM_Module_0000' (I3Tray.py:76 in _create_name)
INFO (I3Tray): Adding Anonymous Module of type '<class 'generatePOCAM_Module.GeneratePOCAM_Module'>' with name 'GeneratePOCAM_Module_0001' (I3Tray.py:76 in _create_name)
INFO (I3Tray): Adding Anonymous Service of type 'I3SPRNGRandomServiceFactory' with name 'I3SPRNGRandomServiceFactory_0000' (I3Tray.py:76 in _create_name)
INFO (I3Tray): Adding Anonymous Segment of type 'I3CLSimMakeHits' with name 'I3CLSimMakeHits_0000' (I3Tray.py:76 in _create_name)
Traceback (most recent call last):
  File "scripts/all_in_one_POCAM.py", line 140, in <module>
    **common_clsim_parameters
  File "/Users/fiedl/icecube/builds/2020-04-15_combo_merge-clsim-hole-ice/lib/I3Tray.py", line 224, in AddSegment
    return _segment(self, _name, **kwargs)
  File "/Users/fiedl/icecube/builds/2020-04-15_combo_merge-clsim-hole-ice/lib/icecube/clsim/traysegments/I3CLSimMakeHits.py", line 34, in I3CLSimMakeHits
    return I3CLSimMakePhotons(tray, name, **kwargs)
TypeError: I3CLSimMakePhotons() got an unexpected keyword argument 'ParallelEvents'
```

From a quick search, this option has been removed in https://github.com/IceCube-SPNO/IceTrayCombo/commit/2a03007b7ad66030ac94ed01af46a7d2aa4f722b

> Reimplement I3CLSimMakePhotons in terms of I3CLSimServer
> I3CLSimMakeHits is a thin wrapper around I3CLSimMakePhotons, and
I3CLSimMakeHitsFromPhotons remains unchanged. I3CLSimMakePhotons sets up an
in-process server and then passes it down to I3CLSimMakePhotonsWithServer. A
multi-process runner like IceProd could create the server on its own and pass
its address to multiple client processes running I3CLSimMakePhotonsWithServer
to e.g. share a single GPU with multiple Geant4 instances. See #2160.

However, I have not looked into this change; therefore, I'm not sure if there is a replacement strategy, or if one can simply drop the parameter and let icetray handle the parallelisation.

**Comment by fschmuckermaier** [comment]
dropping `ParallelEvents` works as the parameter is no longer required, probably due to claim server rewrite.
